language: python
python:
  - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install numpy scipy matplotlib PrettyTable
# command to run tests
script:
  - python -m unittest Testing.run_tests
