target-version = "py310"
extend-exclude = [
    "*.ipynb",
]

[lint]
select = [
    # https://docs.astral.sh/ruff/rules/unused-import/
    "F401",
    # https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP",
]
